version: '3'
services: 
    zookeeper: 
        image: wurstmeister/zookeeper
        container_name: Zookeeper_Nasirul
        ports: 
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        container_name: Kafka_Nasirul
        ports: 
            - "9092:9092"
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "kafka_topic_nasirul:1:3"